/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  defaultSidebar: [
    { type: 'autogenerated', dirName: '.' }
  ],
  dataSidebar: [
    { type: 'autogenerated', dirName: 'photoniq' }
  ],
  // devToolsSidebar: [
  //   'development',
  //   {
  //     type: 'category',
  //     label: 'CLI',
  //     items: [
  //       { type: 'autogenerated', dirName: 'cli' },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'SDKs',
  //     items: [
  //       { type: 'autogenerated', dirName: 'sdks' }
  //     ],
  //   },
  // ],
  // releaseNotesSidebar: [
  //   { type: 'autogenerated', dirName: 'release-notes' }
  // ],
  // sampleAppsSidebar: [
  //   { type: 'autogenerated', dirName: 'apps' }
  // ],
};

module.exports = sidebars;
