name: Run Search Indexing
on:
  push:
    branches:
      - main
jobs:
  on_push:
    runs-on: ubuntu-latest
    name: Run DocSearch Scraper
    steps:
      - name: Algolia Docsearch Indexer
        uses: darrenjennings/algolia-docsearch-action@v0.2.0
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          file: 'algolia.config.json'